### PR TITLE
adding log to events

### PR DESCRIPTION
**Pull request by alarangeiras**

### CODE REVIEW

**Comment by rk** [comment]
Hi Allan. I'm skeptical that log output when registering or executing jobs is helpful. What use case are you adding this for?

**Comment by alarangeiras** [comment]
Hi Robert,

We are analysing async job solutions for our backend cases in Go.
It is known that async executions are harder to trace and I found myself in the situation to log whenever it executes.
I thought it would be the API responsability register those calls.
Probably we'll adopt something similar in our projects in the future.

**Comment by rk** [comment]
Well, what's the benefit of having the cron library log its execution? You could just as easily log in one of your cron tasks (which is what I would do). I'm not certain the output from the cron library would be useful when compared against what your task could output.

I'm just trying to evaluate if this would be useful to others, and if I've overlooked something.

**Comment by alarangeiras** [comment]
It is true, I could log the execution inside of my callback function. However, once I delegate the execution to API, should I log it?
Anyway, I thought it would be nicer the API to do that, but I'll understand if you choose discard this pull request.

**Comment by rk** [comment]
Because the cron API manages so little information (just schedule and when to execute, really) I don't think the API should log data itself. If you want logging, it's probably better within your task as you'll have more relevant information.

**Pull request closed without merging**
